# Generated by Django 5.0.7 on 2024-10-01 17:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolmock_app', '0002_classgroup_question_result_school_student_test_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
